export interface Product {
  id: string;
  name: string;
  category: "tra-mate" | "khuyen-mai" | "combo";
  image: string;
  price: number;
  oldPrice?: number;
  rating: number;
  reviewCount: number;
  badge?: string;
  size: string;
  short: string;
}

export interface CategoryCard {
  id: string;
  name: string;
  image: string;
  count: number;
  href: string;
}

export const mateProducts: Product[] = [
  {
    id: "sadu-mate-xa-den",
    name: "Trà Mate Xạ Đen",
    category: "tra-mate",
    image: "/assets/products/tra-xa-den.jpg",
    price: 149000,
    rating: 4.9,
    reviewCount: 302,
    badge: "Bán chạy",
    size: "150g",
    short: "Xạ đen nguyên chất, sao thủ công theo phương pháp truyền thống, giữ trọn hương vị mộc mạc và màu nước cánh gián đẹp mắt.",
  },
  {
    id: "sadu-mate-xa-den-hoa-cuc",
    name: "Trà Mate Xạ Đen Hoa Cúc",
    category: "tra-mate",
    image: "/assets/products/tra-xa-den-hoa-cuc.jpg",
    price: 149000,
    rating: 4.8,
    reviewCount: 156,
    badge: "Mới",
    size: "150g",
    short: "Hoa cúc chi vàng ươm hoà cùng xạ đen, mang lại tách trà dịu êm, hương thơm ấm áp, thích hợp buổi tối.",
  },
  {
    id: "sadu-mate-xa-den-la-sen",
    name: "Trà Mate Xạ Đen Lá Sen",
    category: "tra-mate",
    image: "/assets/products/tra-xa-den-la-sen.jpg",
    price: 149000,
    rating: 4.9,
    reviewCount: 214,
    badge: "Bán chạy",
    size: "150g",
    short: "Xạ đen kết hợp lá sen và hoa sen khô, cho vị trà thanh, hậu ngọt nhẹ, hương sen thoang thoảng dễ chịu.",
  },
];

export const promotionProducts: Product[] = [
  {
    id: "promo-ca-gai-leo-xa-den-1kg",
    name: "Trà Cà Gai Leo Xạ Đen SADU",
    category: "khuyen-mai",
    image: "/assets/products/promo-ca-gai-leo-xa-den-1kg.jpg",
    price: 396000,
    oldPrice: 436000,
    rating: 4.9,
    reviewCount: 278,
    badge: "Giảm giá",
    size: "1kg",
    short: "Mát gan, hỗ trợ tăng cường chức năng gan, thanh lọc cơ thể.",
  },
  {
    id: "promo-ca-gai-leo-1kg",
    name: "Trà Túi Lọc Cà Gai Leo SADU",
    category: "khuyen-mai",
    image: "/assets/products/promo-ca-gai-leo-1kg.jpg",
    price: 396000,
    oldPrice: 436000,
    rating: 4.8,
    reviewCount: 321,
    badge: "Giảm giá",
    size: "1kg",
    short: "Hỗ trợ mát gan, thanh nhiệt, giải độc cơ thể.",
  },
  {
    id: "promo-ca-gai-leo-dinh-lang-1kg",
    name: "Trà Cà Gai Leo Đinh Lăng",
    category: "khuyen-mai",
    image: "/assets/products/promo-ca-gai-leo-dinh-lang-1kg.jpg",
    price: 396000,
    oldPrice: 436000,
    rating: 4.8,
    reviewCount: 204,
    badge: "Giảm giá",
    size: "1kg",
    short: "Hỗ trợ bồi bổ cơ thể, giảm mệt mỏi, tăng sức đề kháng.",
  },
  {
    id: "promo-diep-ca-ca-gai-leo-1kg",
    name: "Trà Diếp Cá Cà Gai Leo",
    category: "khuyen-mai",
    image: "/assets/products/promo-diep-ca-ca-gai-leo-1kg.jpg",
    price: 396000,
    oldPrice: 436000,
    rating: 4.7,
    reviewCount: 166,
    badge: "Giảm giá",
    size: "1kg",
    short: "Thanh nhiệt, hỗ trợ giảm nóng trong, làm mát cơ thể.",
  },
  {
    id: "promo-ca-gai-leo-che-xanh-1kg",
    name: "Trà Cà Gai Leo Chè Xanh",
    category: "khuyen-mai",
    image: "/assets/products/promo-ca-gai-leo-che-xanh-1kg.jpg",
    price: 396000,
    oldPrice: 436000,
    rating: 4.8,
    reviewCount: 187,
    badge: "Giảm giá",
    size: "1kg",
    short: "Chống oxy hóa, thanh nhiệt, hỗ trợ tỉnh táo.",
  },
  {
    id: "promo-ca-gai-leo-rau-ma-1kg",
    name: "Trà Cà Gai Leo Rau Má",
    category: "khuyen-mai",
    image: "/assets/products/promo-ca-gai-leo-rau-ma-1kg.jpg",
    price: 480000,
    oldPrice: 504000,
    rating: 4.9,
    reviewCount: 249,
    badge: "Giảm giá",
    size: "1kg",
    short: "Thanh nhiệt, làm mát cơ thể, hỗ trợ đẹp da.",
  },
  {
    id: "promo-ca-gai-leo-la-oi-1kg",
    name: "Trà Cà Gai Leo Lá Ổi",
    category: "khuyen-mai",
    image: "/assets/products/promo-ca-gai-leo-la-oi-1kg.jpg",
    price: 480000,
    oldPrice: 504000,
    rating: 4.9,
    reviewCount: 291,
    badge: "Giảm giá",
    size: "1kg",
    short: "Hỗ trợ tiêu hóa, hỗ trợ ổn định đường huyết, giảm đầy bụng.",
  },
  {
    id: "promo-ca-gai-leo-tia-to-1kg",
    name: "Trà Cà Gai Leo Tía Tô",
    category: "khuyen-mai",
    image: "/assets/products/promo-ca-gai-leo-tia-to-1kg.jpg",
    price: 480000,
    oldPrice: 504000,
    rating: 4.7,
    reviewCount: 173,
    badge: "Giảm giá",
    size: "1kg",
    short: "Hỗ trợ giải cảm, giảm dị ứng theo mùa, làm ấm cơ thể.",
  },
];

export const comboProducts: Product[] = [
  {
    id: "combo-trung-ga-thao-duoc-3-tang-1",
    name: "Combo 3 tặng 1 · Trứng gà thảo dược SADU",
    category: "combo",
    image: "/assets/products/combo-trung-ga-thao-duoc-sadu.jpg",
    price: 358500,
    rating: 4.9,
    reviewCount: 86,
    badge: "Combo mới",
    size: "Combo quà tặng",
    short: "Trứng không kháng sinh, ăn thảo dược sạch, cholesterol xấu thấp, phù hợp khách cần thực phẩm sạch dùng hằng ngày.",
  },
  {
    id: "combo-la-oi-2-tang-1",
    name: "Combo 2 tặng 1 · Cà Gai Leo Lá Ổi 100g",
    category: "combo",
    image: "/assets/products/combo-ca-gai-leo-la-oi-100g.jpg",
    price: 278000,
    rating: 4.8,
    reviewCount: 138,
    badge: "Flash Sale",
    size: "Combo quà tặng",
    short: "Dùng ảnh đúng dòng Lá Ổi để khách không nhầm sang sản phẩm khác.",
  },
  {
    id: "combo-la-oi-3-tang-2",
    name: "Combo 3 tặng 2 · Cà Gai Leo Lá Ổi 100g",
    category: "combo",
    image: "/assets/products/combo-ca-gai-leo-la-oi-100g.jpg",
    price: 417000,
    rating: 4.9,
    reviewCount: 164,
    badge: "Flash Sale",
    size: "Combo quà tặng",
    short: "Combo mua nhiều cho dòng Lá Ổi, giữ phong cách card sang và dễ nhìn.",
  },
  {
    id: "combo-day-dau-xuong-5-tang-2",
    name: "Combo 5 tặng 2 · Trà túi lọc Dây Đau Xương Cà Gai Leo 250g",
    category: "combo",
    image: "/assets/products/combo-day-dau-xuong-ca-gai-leo.jpg",
    price: 945000,
    rating: 4.7,
    reviewCount: 88,
    badge: "Combo hot",
    size: "250g",
    short: "Đã thay bằng đúng ảnh hộp Dây Đau Xương Cà Gai Leo để khớp tên combo.",
  },
  {
    id: "combo-rau-ma-2-tang-1",
    name: "Combo 2 tặng 1 · Cà Gai Leo Rau Má",
    category: "combo",
    image: "/assets/products/combo-ca-gai-leo-rau-ma-premium.jpg",
    price: 278000,
    rating: 4.8,
    reviewCount: 141,
    badge: "Flash Sale",
    size: "Combo quà tặng",
    short: "Đã thay sang đúng ảnh hộp Rau Má premium theo ảnh bạn gửi để combo nhìn đồng nhất hơn.",
  },
  {
    id: "combo-xa-den-2-tang-1",
    name: "Combo 2 tặng 1 · Cà Gai Leo Xạ Đen",
    category: "combo",
    image: "/assets/products/combo-ca-gai-leo-xa-den-box.jpg",
    price: 278000,
    rating: 4.9,
    reviewCount: 176,
    badge: "Flash Sale",
    size: "Combo quà tặng",
    short: "Đã đổi sang đúng ảnh hộp Xạ Đen để khách nhìn là nhận ra đúng sản phẩm combo.",
  },
  {
    id: "combo-xa-den-3-tang-2",
    name: "Combo 3 tặng 2 · Cà Gai Leo Xạ Đen",
    category: "combo",
    image: "/assets/products/combo-ca-gai-leo-xa-den-box.jpg",
    price: 417000,
    rating: 4.9,
    reviewCount: 193,
    badge: "Flash Sale",
    size: "Combo quà tặng",
    short: "Combo số lượng lớn cho dòng Xạ Đen, đã đồng bộ ảnh hộp theo đúng ảnh tham chiếu.",
  },
  {
    id: "combo-la-oi-3-tang-1",
    name: "Combo 3 tặng 1 · Cà Gai Leo Lá Ổi",
    category: "combo",
    image: "/assets/products/combo-ca-gai-leo-la-oi-100g.jpg",
    price: 447000,
    rating: 4.8,
    reviewCount: 121,
    badge: "Combo hot",
    size: "Combo quà tặng",
    short: "Combo Lá Ổi dành cho khách thích packshot màu cam và vị trà dễ uống.",
  },
  {
    id: "combo-la-oi-5-tang-3",
    name: "Combo 5 tặng 3 · Cà Gai Leo Lá Ổi",
    category: "combo",
    image: "/assets/products/combo-ca-gai-leo-la-oi-100g.jpg",
    price: 695000,
    rating: 4.9,
    reviewCount: 109,
    badge: "Combo hot",
    size: "Combo quà tặng",
    short: "Ưu đãi sâu hơn cho khách chốt số lượng lớn dòng Lá Ổi.",
  },
  {
    id: "combo-dinh-lang-5-tang-3",
    name: "Combo 5 tặng 3 · Cà Gai Leo Đinh Lăng",
    category: "combo",
    image: "/assets/products/combo-ca-gai-leo-dinh-lang-box.jpg",
    price: 695000,
    rating: 4.8,
    reviewCount: 97,
    badge: "Combo hot",
    size: "Combo quà tặng",
    short: "Đã thay sang đúng ảnh hộp Đinh Lăng mới để người xem không bị lệch nhận diện sản phẩm.",
  },
  {
    id: "combo-mate-xa-den-3-tang-1",
    name: "Combo 3 tặng 1 · Trà Mate Xạ Đen 150g",
    category: "combo",
    image: "/assets/products/tra-xa-den.jpg",
    price: 447000,
    rating: 4.9,
    reviewCount: 145,
    badge: "Tặng thêm",
    size: "150g",
    short: "Ảnh đúng hộp Mate Xạ Đen, phù hợp card combo premium.",
  },
  {
    id: "combo-mate-xa-den-5-tang-2",
    name: "Combo 5 tặng 2 · Trà Mate Xạ Đen 150g",
    category: "combo",
    image: "/assets/products/tra-xa-den.jpg",
    price: 745000,
    rating: 4.9,
    reviewCount: 132,
    badge: "Tặng thêm",
    size: "150g",
    short: "Combo cao cấp cho dòng Mate Xạ Đen, phù hợp bán kèm quà tặng.",
  },
  {
    id: "combo-mate-la-sen-3-tang-1",
    name: "Combo 3 tặng 1 · Trà Mate Xạ Đen Lá Sen",
    category: "combo",
    image: "/assets/products/tra-xa-den-la-sen.jpg",
    price: 447000,
    rating: 4.8,
    reviewCount: 118,
    badge: "Tặng thêm",
    size: "150g",
    short: "Ảnh đúng hộp Lá Sen giúp section combo vẫn đồng nhất với hình thực tế.",
  },
  {
    id: "combo-mate-la-sen-5-tang-2",
    name: "Combo 5 tặng 2 · Trà Mate Xạ Đen Lá Sen",
    category: "combo",
    image: "/assets/products/tra-xa-den-la-sen.jpg",
    price: 745000,
    rating: 4.9,
    reviewCount: 101,
    badge: "Tặng thêm",
    size: "150g",
    short: "Combo quà tặng số lượng lớn cho khách thích hương lá sen thanh mát.",
  },
];

export const products: Product[] = [...mateProducts, ...promotionProducts, ...comboProducts];

export const categories: CategoryCard[] = [
  {
    id: "tra-mate",
    name: "Bộ sưu tập Mate",
    image: "/assets/products/tra-xa-den.jpg",
    count: mateProducts.length,
    href: "#mate-collection",
  },
  {
    id: "khuyen-mai",
    name: "Trà túi lọc khuyến mại",
    image: "/assets/products/promo-ca-gai-leo-xa-den-1kg.jpg",
    count: promotionProducts.length,
    href: "#promo-products",
  },
  {
    id: "combo",
    name: "Combo khuyến mại",
    image: "/assets/products/tra-xa-den-la-sen.jpg",
    count: comboProducts.length,
    href: "#bundle",
  },
];

export function formatVnd(value: number): string {
  return value.toLocaleString("vi-VN") + "đ";
}
